"""empty message

Revision ID: 4eea0250de8e
Revises: 9fee688071f8
Create Date: 2021-02-05 14:43:05.527309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eea0250de8e'
down_revision = '9fee688071f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer_info', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_info', type_='unique')
    # ### end Alembic commands ###
