"""empty message

Revision ID: 827ed4e8e96e
Revises: a1df1b339598
Create Date: 2021-02-05 04:19:00.761768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827ed4e8e96e'
down_revision = 'a1df1b339598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_info', sa.Column('user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'customer_info', 'user_profile', ['user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_info', type_='foreignkey')
    op.drop_column('customer_info', 'user')
    # ### end Alembic commands ###
