"""'initial_migration'

Revision ID: 9a54f4f3a9b7
Revises: 
Create Date: 2021-02-03 00:19:03.835770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a54f4f3a9b7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('contacts', sa.String(length=10), nullable=False),
    sa.Column('tel', sa.String(length=15), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('isfollow', sa.Boolean(), nullable=True),
    sa.Column('baseinfo', sa.String(length=400), nullable=True),
    sa.Column('structure', sa.String(length=400), nullable=True),
    sa.Column('structuresrc', sa.String(length=256), nullable=True),
    sa.Column('decision', sa.String(length=400), nullable=True),
    sa.Column('network', sa.String(length=400), nullable=True),
    sa.Column('networksrc', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('follow_info',
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('content', sa.String(length=400), nullable=False),
    sa.Column('customerid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customerid'], ['customer_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
