"""'initial_migration1'

Revision ID: a1df1b339598
Revises: 9a54f4f3a9b7
Create Date: 2021-02-03 01:29:22.512313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1df1b339598'
down_revision = '9a54f4f3a9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='user_profile')
    op.drop_column('user_profile', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('name', mysql.VARCHAR(length=32), nullable=False))
    op.create_index('name', 'user_profile', ['name'], unique=True)
    # ### end Alembic commands ###
